### PR TITLE
Astro 🚀 - Replacing Docsify

### PR DESCRIPTION
**Pull request by Wright4i**
@codefori/core I went out on a limb here so I'm really curious what your opinions are. I was playing around with Astro and Starlight for my personal github pages [site](https://wright4i.github.io/) and thought it'd be really cool to implement it on the codefori docsite too.

Here is a live build running on my fork: https://wright4i.github.io/docs/

Astro and Starlight (powered by Astro) is a very easy to use Document site with tons of power, off by default, focused on speed, efficiency, server side rendering, uses typescript and completely framework agnostic so we can do whatever we want without limitation. Plus it happens to use Shiki which I knew I could get our tmLanguages running on so we can actually have syntax highlighed IBM i Languages!

# Major Changes
* Out with Docsify, in with [Astro Starlight](https://starlight.astro.build/)
* Added RPGLE and CL syntax highlighting with the [vscode-ibmi-languages](https://github.com/barrettotte/vscode-ibmi-languages/)
* I8n support (We're ready to start translation to Danish & French). It includes fallback support so if a page is untranslated it won't be an issue.
* Added hover on zoom for smaller `<Card>` images
* Documentation and side bar will auto-generate for most subfolders making future documentation easier.
* Every page converted to `MDX` which is Markdown format with embeddable typescript. This was done to use Starlight's built-in components. We can make more complicated `.astro` ones if needed. `MDX` files also contain frontmatter, a metadata markup at the top that controls its title/description/ordering etc.
* Table of Contents on right side - automatically generated from headers
* Page Navigation and `Edit page` links on bottom of every page

# Minor Changes
* Fixed dead halycon-tech links (and clicked every other link many, many, times..)
* Small typos corrected
* Removed bad image links (1) and unused images
* We had 2 `Developing` Sidebar sections. I left the first one for the `/developing` folder and the `/dev` folder was renamed `Extension Development`
* Added `<Icon>` after each link to signify external links, github, youtube, and "vendor/sponsor" links with internal doc links left icon-less.
* Went through all code blocks to ensure they had a language specified
* Added titles, terminals frames, highlighting, and file names to make code blocks prettier
* Added `<Tabs>` and `<TabItem>` to a 2 spots where a comparison was happening and it felt right

# What I intentionally didn't change / tried to recreate in Astro
* Content
* Theming
* /docs/ url
* Layout:
1. Replaced `<!-- panels div left/div right -->` with `<CardGrid>` and `<Card>`
2. Replaced `[!WARNING|NOTE|TIP]` with `<Aside>`

## Workflow Change
* Included the `.github/workflows/astro.yml` workflow file used to build the site. Make sure the Github Pages source is `Github Actions` in `Settings > Pages > Build and deployment`

### CODE REVIEW

**Comment by worksofliam** [comment]
@Wright4i Any chance I can get you to fix those simple conflicts? I suspect this is going to be merged this week honestly.

**Comment by Wright4i** [comment]
@worksofliam resolved and rebuild complete on demo site

**Comment by SJLennon** [comment]
@Wright4i 

Couple of comments:
1) I like the new wider middle column, but with my setup the right column is cut off .  Below is what I see on Win10, where I'm running 1080 but with 125% scaling (old eyes), but I'm probably an exception--this is just feedback and I understand this is tricky. I see everything if I change to the 100% recommended resolution.
2) I have to click on the image now to get the zoom out and hold the click because releasing the button causes it to zoom back in. I kind of liked the prior hover approach where it remained zoomed until I hit escape. Again, just feedback.
image

**Comment by Wright4i** [comment]
@SJLennon not a problem. I tested multiple resolutions but didn't think to lower my resolution **and** increase the zoom. The fix is quite simple - just had to set `min-width` for the sidebar to the `--sl-sidebar-width` and voilà!

## Sidebar toc not being cut-off (1080p + 125% zoom)
image

Hovering should work again - had to lower the transform scale from 4 to 2 because of the larger content-area, but I changed from :hover to :active which changed the behavior which was unintended.

Give it another shot and let me know. We've got a wide range of users so this feedback helps!

**Comment by worksofliam** [comment]
@Wright4i The sizing issues you made here are really nice. Thanks for taking feedback and working with it so quickly!

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@Wright4i Thanks for bringing a new fresh look to to Code for IBM i documentation - I like i a lot 😍

I'm just wondering why some of the headers in the left part of the screen looks like this:

image

image

**Comment by Wright4i** [comment]
> I'm just wondering why some of the headers in the left part of the screen looks like this:

@chrjorgensen Those are badges. More than happy to change or remove them.

```ts
interface BadgeConfig {
  text: string;
  variant: 'note' | 'tip' | 'caution' | 'danger' | 'success' | 'default';
}
```

**Comment by worksofliam** [comment]
@Wright4i 

I make a lot of use of this style throughout the docs, but I don't think we ever had the box outline before. Is it easy to remove that?

image

image

**Comment by Wright4i** [comment]
@worksofliam removed the card border see below / demo site:

image

**Pull request merged**
